name: Check Issues
on:
  issues:
    types: [opened, edited, reopen]

jobs:
  autoclose:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: check issue
        uses: bdsx/issue-closer@HEAD
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
